# Label configuration aligned with Conventional Commits taxonomy.
"type:feature":
  - head-branch:
      - "^feat"
      - "^feature"
  - changed-files:
      - any-glob-to-any-file: "src/**"
      - any-glob-to-any-file: "tests/**"

"type:fix":
  - head-branch:
      - "^fix"
      - "^hotfix"
  - changed-files:
      - any-glob-to-any-file: "src/**"
      - any-glob-to-any-file: "tests/**"

"type:docs":
  - head-branch:
      - "^docs"
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: "templates/**"

"type:ci":
  - head-branch:
      - "^ci"
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
      - any-glob-to-any-file: "scripts/**"

"type:chore":
  - head-branch:
      - "^chore"
  - changed-files:
      - any-glob-to-any-file: ".github/**"
      - any-glob-to-any-file: "Makefile"
      - any-glob-to-any-file: "templates/**"

"scope:dependencies":
  - head-branch:
      - "^deps"
      - "^renovate"
  - changed-files:
      - any-glob-to-any-file: "renovate.json"
      - any-glob-to-any-file: "uv.lock"
      - any-glob-to-any-file: "requirements*.txt"
      - any-glob-to-any-file: "pyproject.toml"

"scope:governance":
  - changed-files:
      - any-glob-to-any-file: "docs/governance/**"
      - any-glob-to-any-file: "docs/adr/**"
      - any-glob-to-any-file: "Next_Steps.md"
