[tool.ruff]
line-length = 100
extend-exclude = ["data"]
src = ["src", "scripts", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
addopts = "--maxfail=1 --disable-warnings --cov=src --cov-report=term-missing"
pythonpath = ["src"]

[tool.mypy]
python_version = "3.13"
namespace_packages = true
packages = ["hotpass"]
strict = false
mypy_path = ["src"]
warn_unused_configs = true
ignore_missing_imports = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
skip_empty = true
