[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hotpass"
version = "0.1.0"
description = "Hotpass data refinement pipeline"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = "LicenseRef-Proprietary"
dependencies = [
  "pandas>=2.0.0",
  "openpyxl>=3.1.0",
  "pandera>=0.18.0",
  "great-expectations>=0.18.0",
  "phonenumbers>=8.13.0",
  "rich>=13.0.0",
  "pyyaml>=6.0.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.3.0",
  "pytest-cov>=5.0.0",
  "mypy>=1.12.0",
  "ruff>=0.6.0",
  "bandit>=1.7.10",
  "black>=24.8.0",
  "pre-commit>=3.7.0",
  "detect-secrets>=1.5.0",
]

docs = [
  "sphinx>=7.3.0",
  "myst-parser>=2.0.0",
  "sphinx-autodoc-typehints>=2.3.0",
  "furo>=2024.8.6",
]

[project.scripts]
hotpass = "hotpass.cli:main"

[tool.ruff]
line-length = 100
extend-exclude = ["data"]
src = ["src", "scripts", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
addopts = "--maxfail=1 --disable-warnings --cov=src --cov-report=term-missing"
pythonpath = ["src"]

[tool.mypy]
python_version = "3.12"
namespace_packages = true
packages = ["hotpass"]
strict = false
mypy_path = ["src"]
warn_unused_configs = true
ignore_missing_imports = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
skip_empty = true
