services:
  marquez-db:
    image: postgres:14
    platform: linux/amd64
    container_name: marquez-db
    environment:
      POSTGRES_DB: marquez
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U marquez
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - marquez_db:/var/lib/postgresql/data

  marquez:
    image: marquezproject/marquez:0.50.0
    platform: linux/amd64
    container_name: marquez
    depends_on:
      marquez-db:
        condition: service_healthy
    environment:
      MARQUEZ_PORT: 5000
      MARQUEZ_UI_PORT: 3000
      MARQUEZ_ADMIN_PORT: 5001
      MARQUEZ_DB_HOST: marquez-db
      MARQUEZ_DB_PORT: 5432
      MARQUEZ_DB_NAME: marquez
      MARQUEZ_DB_USER: marquez
      MARQUEZ_DB_PASSWORD: marquez
    ports:
      - "${MARQUEZ_API_PORT:-5000}:5000"
      - "${MARQUEZ_UI_PORT:-3000}:3000"
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO- http://localhost:3000 > /dev/null
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  marquez_db:
    driver: local
