"""Pipeline event names shared across CLI and orchestration layers."""

from __future__ import annotations

__all__ = [
    "PIPELINE_EVENT_START",
    "PIPELINE_EVENT_LOAD_STARTED",
    "PIPELINE_EVENT_LOAD_COMPLETED",
    "PIPELINE_EVENT_AGGREGATE_STARTED",
    "PIPELINE_EVENT_AGGREGATE_PROGRESS",
    "PIPELINE_EVENT_AGGREGATE_COMPLETED",
    "PIPELINE_EVENT_SCHEMA_STARTED",
    "PIPELINE_EVENT_SCHEMA_COMPLETED",
    "PIPELINE_EVENT_EXPECTATIONS_STARTED",
    "PIPELINE_EVENT_EXPECTATIONS_COMPLETED",
    "PIPELINE_EVENT_WRITE_STARTED",
    "PIPELINE_EVENT_WRITE_COMPLETED",
    "PIPELINE_EVENT_COMPLETED",
]

PIPELINE_EVENT_START = "pipeline.start"
PIPELINE_EVENT_LOAD_STARTED = "load.started"
PIPELINE_EVENT_LOAD_COMPLETED = "load.completed"
PIPELINE_EVENT_AGGREGATE_STARTED = "aggregate.started"
PIPELINE_EVENT_AGGREGATE_PROGRESS = "aggregate.progress"
PIPELINE_EVENT_AGGREGATE_COMPLETED = "aggregate.completed"
PIPELINE_EVENT_SCHEMA_STARTED = "schema.started"
PIPELINE_EVENT_SCHEMA_COMPLETED = "schema.completed"
PIPELINE_EVENT_EXPECTATIONS_STARTED = "expectations.started"
PIPELINE_EVENT_EXPECTATIONS_COMPLETED = "expectations.completed"
PIPELINE_EVENT_WRITE_STARTED = "write.started"
PIPELINE_EVENT_WRITE_COMPLETED = "write.completed"
PIPELINE_EVENT_COMPLETED = "pipeline.completed"
