---
apiVersion: actions.github.com/v1alpha1
kind: RunnerScaleSet
metadata:
  name: hotpass-arc
  namespace: arc-runners
spec:
  githubConfigRef:
    name: hotpass-github-config
  minRunners: 0
  maxRunners: 20
  runnerScaleSetName: hotpass-arc
  template:
    metadata:
      labels:
        workflows.hotpass.dev/tier: pipeline
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:2.321.0
          env:
            - name: ACTIONS_RUNNER_DEBUG
              value: "false"
            - name: ACTIONS_RUNNER_SCOPE
              value: repository
          resources:
            requests:
              cpu: 2000m
              memory: 8Gi
            limits:
              cpu: 4000m
              memory: 16Gi
      serviceAccountName: arc-runners
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: dedicated
          operator: Equal
          value: hotpass-ci
          effect: NoSchedule
---
apiVersion: actions.github.com/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: hotpass-arc
  namespace: arc-runners
spec:
  scaleTargetRef:
    name: hotpass-arc
  minReplicas: 0
  maxReplicas: 20
  scaleUpTriggers:
    - githubEvent: { workflowJob: {} } # scale on workflow demand
      amount: 5
      duration: 5m
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - IAmJonoBo/Hotpass
      scaleUpThreshold: 1
      scaleDownThreshold: 0
      scaleDownDelaySecondsAfterScaleOut: 120
      scaleDownDelaySecondsAfterScaleIn: 60
