name: ARC runner smoke test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  lifecycle-check:
    name: Verify ARC runner lifecycle
    runs-on:
      - self-hosted
      - hotpass-arc
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for ARC runner
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARC_RUNNER_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: |
          python -m pip install -U uv
          uv venv
          uv sync --extra orchestration

      - name: Verify runner lifecycle
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name || github.repository }}
        run: |
          OWNER=${GITHUB_OWNER}
          REPO=${GITHUB_REPOSITORY_NAME#*/}
          uv run python scripts/arc/verify_runner_lifecycle.py \
            --owner "${OWNER}" \
            --repository "${OWNER}/${REPO}" \
            --scale-set hotpass-arc \
            --namespace arc-runners \
            --timeout 300
