name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up uv and Python 3.13
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7
        with:
          python-version: "3.13"

      - name: Synchronise dependencies (dev + docs)
        run: |
          set -euo pipefail
          uv sync --extra dev --extra docs --frozen || uv sync --extra dev --extra docs

      - name: Prime pre-commit hooks
        run: uv run pre-commit install --install-hooks

      - name: Ensure Prefect CLI is available
        run: |
          set -euo pipefail
          uv run python -m pip install --quiet --upgrade "prefect>=3.0.0"

      - name: Configure Prefect for offline execution
        run: |
          set -euo pipefail
          uv run python -m prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
          uv run python -m prefect config set PREFECT_ENABLE_ANALYTICS=false
