name: Docker Build Cache

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: docker-cache-${{ github.ref }}
  cancel-in-progress: false

jobs:
  warm-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build image with cache hydration
        uses: docker/build-push-action@4f58a0e7cbfbadccdbf6f1a12e920060f136cc7d # v6
        with:
          context: .
          file: Dockerfile
          push: false
          load: false
          tags: ghcr.io/hotpass/cache:${{ github.sha }}
          cache-from: type=gha,scope=hotpass-${{ github.ref_name }}
          cache-to: type=gha,scope=hotpass-${{ github.ref_name }},mode=max
