name: docs

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - "IMPLEMENTATION_STATUS.md"
      - "IMPLEMENTATION_COMPLETE.md"
      - "RELEASE_SUMMARY.md"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync dependencies
        run: |
          uv venv
          uv sync --extra docs

      - name: Build documentation
        run: uv run sphinx-build -n -W -b html docs docs/_build/html

      - name: Check documentation links
        run: uv run sphinx-build -b linkcheck docs docs/_build/linkcheck
