name: Process and Refine Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Ruff lint
      run: ruff check

    - name: Ruff formatting check
      run: ruff format --check

    - name: Pytest
      run: pytest

    - name: Mypy
      run: mypy src tests scripts

    - name: Bandit
      run: bandit -r src scripts

  process-data:
    runs-on: ubuntu-latest
    needs: qa
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run data processing script
      run: python scripts/process_data.py

    - name: Upload refined data
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: refined-data
        path: data/refined_data.xlsx