name: release-drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
