name: zap-baseline

on:
  workflow_dispatch:
    inputs:
      target:
        description: URL to scan (defaults to local Streamlit)
        required: false
        default: http://127.0.0.1:8501

permissions:
  contents: read

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --extra dev --extra dashboards --frozen || uv sync --extra dev --extra dashboards

      - name: Launch Streamlit (if local)
        if: inputs.target == 'http://127.0.0.1:8501'
        run: |
          nohup uv run streamlit run src/hotpass/dashboard.py --server.headless true --server.port 8501 &
          sleep 15

      - name: OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@6c5a007541891231cd9e0ddec25d4f25c59c9874 # v0.15.0
        with:
          target: ${{ inputs.target }}
          fail_action: false

      - name: Upload ZAP report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: zap-report
          path: zap_report.html
